---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: db
  namespace: flux-system
spec:
  #  dependsOn:
  #  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
  #      kind: Kustomization
  #      name: namespaces
  #      namespace: flux-system
  chart:
    spec:
      chart: postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lfs269
  interval: 1m0s
  storageNamespace: instavote
  targetNamespace: instavote
  values:
    service:
      name: db
    settings:
      authMethod: trust
