---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1m
  ref:
    branch: main
  timeout: 1m0s
  secretRef:
    name: github-instavote-deploy
  url: https://github.com/joaquimcampos/instavote-deploy.git
