---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: vote
  namespace: instavote
spec:
  digestReflectionPolicy: Never
  filterTags:
    extract: $ts
    pattern: ^main-[a-f0-9]+-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: vote
  policy:
    numerical:
      order: asc
