---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: vote
  namespace: instavote
spec:
  exclusionList:
  - ^.*\.sig$
  image: jcampos15/vote
  interval: 1m0s
  provider: generic
