apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote
  namespace: instavote
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
